@switch($type)
    @case('noob')
    @component('components.pricing.card')
        @slot('cardClass')
            white-pricing-card
        @endslot
        @slot('image')
            images/kite.png
        @endslot
        @slot('title')
            Noob
        @endslot
        @slot('description')
            Description
        @endslot
        @slot('price')
            10$
        @endslot
        @slot('button')
            blue
        @endslot
        @slot('modalButton')
            noob
        @endslot
    @endcomponent
    @break

    @case('normal')
    @component('components.pricing.card')
        @slot('cardClass')
            blue-pricing-card
        @endslot
        @slot('image')
            images/paper-plane.png
        @endslot
        @slot('title')
            Normal
        @endslot
        @slot('description')
            Description
        @endslot
        @slot('price')
            10$
        @endslot
        @slot('button')
            white
        @endslot
        @slot('modalButton')
            normal
        @endslot
    @endcomponent
    @break

    @case('hero')
    @component('components.pricing.card')
        @slot('cardClass')
            deep-blue-pricing-card
        @endslot
        @slot('image')
            images/rocket.png
        @endslot
        @slot('title')
            Hero
        @endslot
        @slot('description')
            Description
        @endslot
        @slot('price')
            10$
        @endslot
        @slot('button')
            black
        @endslot
        @slot('modalButton')
            hero
        @endslot
    @endcomponent
    @break

@endswitch